### PR TITLE
Enabled emterpreter option and emscripten_sleep

### PR DESCRIPTION
**Pull request by bzwheeler**
WIP!

This PR enables the `EMTERPRETIFY` and `EMTERPRETIFY_ASYNC` flags for emscripten which allows us to use emscripten_sleep in a non-blocking manner.

The build works, however, there are a few places for improvement.

 * `EMTERPRETIFY` requires separate memory init files which makes the build a bit more complicated and the current "solution" was to add a `--pre-js` script that specifies where to find those files.  This isn't ideal for a number of reasons.
  * the path is hardcoded and is only accurate for the build and not for the final pypy.vm.js.mem release.
  * The generated pypy.vm.js.mem file is currently not copied to the build directory and must be manually copied from `/tmp/usession-unknown-current/testing_1/pypy.vm.js.mem` after the build completes.
  * The final pypy.vm.js file contains the contents of the pre file which isn't necessary
 * Currently nothing is explicity whitelisted or blacklisted so everything uses the emterpreter
 * The docker image rfkelly/pypyjs-build has a version of emcc that does not support the 'asyncFinalizers' api for determining when an async method is complete, see [emscripten issue 3451](https://github.com/kripken/emscripten/issues/3451) so a hacky polling approach is currently used.

### CODE REVIEW

**Comment by rfk** [comment]
> The docker image rfkelly/pypyjs-build has a version of emcc that does not support the 'asyncFinalizers' api

FYI I just pushed an updated docker image which should support this new API.

**Comment by albertjan** [comment]
@bzwheeler I kinda sorta may have done something wrong here :smile:

**Comment by albertjan** [comment]
Oh and it should probably be moved to pypyjs/pypy

**Comment by jedie** [comment]
Oh, i see this for the first time.

What's the status?

> Oh and it should probably be moved to pypyjs/pypy

Yes, a good idea ;)

**Comment by bzwheeler** [comment]
Haven't had time to revisit this yet and probably won't for a good while. Closing for now and will most likely re-open at a later date when it is in better shape.

**Pull request closed without merging**
